remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Rubbish_Du's home
subtitle: There are dreams in life,and each is wonderful.
description: There are dreams in life,and each is wonderful.
author: Rubbish_Du
